- name: deploy mongodb
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    remote_src: yes

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb
    state: present

