- name: Install maven
  ansible.builtin.package:
    name: maven
    state: installed

- name: adding the user roboshop
  ansible.builtin.user:
    name: roboshop
    comment: user added


- name: download and deploy
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/shipping/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: moving the resp files
  ansible.builtin.copy:
    src: /tmp/shipping-main/
    dest: /home/roboshop/shipping
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: clean pkg and mving the target jar 
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/shipping              # Changing the working directory to somedir/ before executing the command
  
- name: moving of systemd service
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/shipping.service

- name: Restarting Service 
  ansible.builtin.systemd:
    state: restarted
    name: shipping
    daemon_reload: yes
    enabled: true 