- name: handson bash  
  hosts: all 
  tasks: 
    - name: Printing teh uptime of the severs 
      ansible.builtin.shell: uptime
      register: started
    - name: Printing start time  
      ansible.builtin.debug:
        msg: heyy i'm {{started}} on