- name: play1
  hosts: all
  vars: 
    LINK: global.com                                    
  tasks:
    - name: TASK 1 shoould be where is the link ??
      ansible.builtin.debug:
        msg: "{{LINK}}"
    - name: TASK 2 direct link ??
      ansible.builtin.debug:
        msg: here is the link {{LINK}}
      vars:
        LINK: local.com                                       
