- name: play1
  hosts: all
  vars: 
    LINK: global.com 
  vars_files:
    file.yml  
  vars_prompt:
    - name: LINK 
      prompt: Enter LINK Value 
      private: true                               
  tasks:
    - name: TASK 1 should be where is the link ??
      ansible.builtin.debug:
        msg: "{{LINK}}"
    - name: TASK 2 direct link ??
      ansible.builtin.debug:
        msg: here is the link {{LINK}}
      vars:
        LINK: local.com                       
    - name: TASK 3 should be where is the command link ??
      ansible.builtin.debug:
        msg: command link is {{cmnd_link}}
    - name: TASK 4 should be where is the file link ??
      ansible.builtin.debug:
        msg: "{{LINK}}"   
    - name: TASK 5 should be where is the prompt link ??
      ansible.builtin.debug:
        msg: "{{LINK}}"                               
