- name: Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: yum repo 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install rabbitmq
  ansible.builtin.package:
    name: rabbitmq-server
    state: installed

- name: Restarting Service 
  ansible.builtin.systemd:
    state: restarted
    name: rabbitmq-server
    daemon_reload: yes
    enabled: true 

- name: Add rabbit-mq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present