- name: installing node js repos
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: adding the user roboshop
  ansible.builtin.user:
    name: roboshop
    comment: user added
